apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: argocd-repo-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: repo-server
      app.kubernetes.io/name: argocd-repo-server-metrics
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
  - port: http-metrics
    path: /metrics
  