{
 "title": "VictoriaMetrics - operator",
 "description": "Overview for operator VictoriaMetrics v0.25.0 or higher",
 "tags": [
  "operator",
  "VictoriaMetrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(operator_log_messages_total,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(operator_log_messages_total{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(vm_app_version{job=\"$job\", instance=\"$instance\"},  version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"text-align: center;\">$version</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CRD Objects count by controller",
   "type": "stat",
   "description": "Number of objects at kubernetes cluster per each controller",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(operator_controller_objects_count{job=~\"$job\",instance=~\"$instance\"}) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_app_uptime_seconds{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reconciliation rate by controller",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=~\"$job\",instance=~\"$instance\",result=~\"requeue_after|requeue|success\"}[$__rate_interval])) by(controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Log message rate",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(operator_log_messages_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (level)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "reconcile errors by controller",
   "type": "graph",
   "description": "Non zero metrics indicates about error with CR object definition (typos or incorrect values) or errors with kubernetes API connection.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by(controller) > 0 ",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=~\"$job\",instance=~\"$instance\",result=\"error\"}[$__rate_interval])) by(controller) > 0",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "throttled reconcilation events",
   "type": "graph",
   "description": "Operator limits number of reconcilation events to 5 events per 2 seconds.\n For now, this limit is applied only for vmalert and vmagent controllers.\n It should reduce load at kubernetes cluster and increase operator performance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(operator_reconcile_throttled_events_total[$__rate_interval])) by(controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Wokring queue depth",
   "type": "graph",
   "description": "Number of objects waiting in the queue for reconciliation. Non-zero values indicate that operator cannot process CR objects changes with the given resources.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(workqueue_depth{job=~\"$job\",instance=~\"$instance\"}) by (name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Reconcilation latency by controller",
   "type": "graph",
   "description": " For controllers with StatefulSet it's ok to see latency greater then 3 seconds. It could be vmalertmanager,vmcluster or vmagent in statefulMode.\n\n For other controllers, latency greater then 1 second may indicate issues with kubernetes cluster or operator's performance.\n ",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(controller_runtime_reconcile_time_seconds_bucket[$__rate_interval])) by(le,controller) )",
     "legendFormat": "q.99 {{controller}}"
    }
   ]
  },
  {
   "title": "resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage ($instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=~\"$job\", instance=~\"$instance\"}) ",
     "legendFormat": "requested from system"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"}) ",
     "legendFormat": "heap inuse"
    },
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "resident"
    }
   ]
  },
  {
   "title": "CPU ($instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU cores used"
    }
   ]
  },
  {
   "title": "Goroutines ($instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "GC duration ($instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n/\nsum(rate(go_gc_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "avg gc duration"
    }
   ]
  }
 ]
}