apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cilium-hubble-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hubble
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
  - port: hubble-metrics