apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmoperator
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: victoria-metrics-operator
  endpoints:
    - port: http
      
  namespaceSelector:
    matchNames:
      - "victoria-metrics-operator"