apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: fluentbit-system
  labels:
    app.kubernetes.io/name: fluentbit
spec:
  selector:
    matchLabels:
      name: fluentbit
  template:
    metadata:
      labels:
        name: fluentbit
    spec:
      serviceAccountName: fluentbit-daemonset
      containers:
        - name: fluent-bit
          imagePullPolicy: Always
          image: cr.fluentbit.io/fluent/fluent-bit
          # args:
          #   - -c 
          #   - /etc/fluent-bit/fluent-bit.conf
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: fluentbit-config
              mountPath: /fluent-bit/etc
          env:
            - name: BASELIME_API_KEY
              valueFrom:
                secretKeyRef:
                  name: baselime-api-key
                  key: BASELIME_API_KEY
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 512Mi
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: fluentbit-config
          configMap:
            name: fluentbit-config