apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: fluentbit-system-auth
  namespace: fluentbit-system
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: read-baselime
    serviceAccount: default