apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: baselime-api-key
  namespace: fluentbit-system
spec:
  type: kv-v2
  mount: kv
  path: fluent-bit/baselime
  destination:
    name: baselime-api-key
    create: true
    overwrite: false
  refreshAfter: 120s
  vaultAuthRef: fluentbit-system-auth
  rolloutRestartTargets:
    - kind: DaemonSet
      name: fluentbit