apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tunamaguro/home-kubernetes-metrics.git
    path: fluent-bit
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fluent-bit
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true