apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/grafana/helm-charts
    path: grafana-operator
    targetRevision: v5.6.3
    chart: grafana-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
