apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-storage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://operator.min.io
    targetRevision: 5.0.13
    chart: tenant
    helm:
      valuesObject:
        # 完全に外部からのアクセスを想定しないので、べた書きする
        secrets:
          name: myminio-env-configuration
          accessKey: loki-storage
          secretKey: loki-storage-secret
        tenant:
          name: loki-storage
          image:
            # https://github.com/minio/minio/issues/18365
            repository: quay.io/minio/minio
            tag: RELEASE.2024-03-15T01-07-19Z-cpuv1
          pools:
            - servers: 1
              name: pool-0
              volumesPerServer: 1
              storageClassName: ceph-rbd
              size: 2Gi
          logging: 
            json: true
          requestAutoCert: true
          buckets:
          # loki buckets https://grafana.com/docs/loki/latest/setup/install/helm/install-scalable/
            - name: chunks
              region: us-east-1
            - name: ruler
              region: us-east-1
            - name: admin
              region: us-east-1

  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
