apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.47.1
    chart: loki
    helm:
      valuesObject:      
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
            type: s3
            s3:
              # 完全に外部からのアクセスを想定しないのでべた書きする
              accessKeyId: loki-storage
              secretAccessKey: loki-storage-secret
              endpoint: https://minio.grafana-loki.svc.cluster.local:443
              s3ForcePathStyle: true
        monitoring:
          dashboards:
            enabled: false
          rules:
            enabled: false
          serviceMonitor:
            enabled: false
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false
        # 必要そうであればhpaを有効にする
        write:
          replicas: 1
        read:
          replicas: 1
        backend:  
          replicas: 1
        test:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      