apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.15.5
    chart: promtail
    helm: 
      valuesObject:
        config:
          clients:
            - url: http://loki-gateway/loki/api/v1/push
  destination:
      server: "https://kubernetes.default.svc"
      namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true