apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-k8s-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://victoriametrics.github.io/helm-charts/'
    targetRevision: 0.23.1
    chart: victoria-metrics-k8s-stack
    helm:
      valuesObject:
        victoria-metrics-operator:
          enabled: false
        defaultRules:
          create: false
        defaultDashboardsEnabled: false
        experimentalDashboardsEnabled: false
        vmsingle:
          enabled: false
        vmcluster:
          enabled: true
          spec:
            retentionPeriod: "90"
            replicationFactor: 1
            vmstorage:
              replicaCount: 1
              storageDataPath: "/vm-data"
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: "ceph-rbd"
                    resources:
                      requests:
                        storage: 10Gi
              resources:
                requests:
                  cpu: 100m
                  memory: 500Mi
                limits:
                  cpu: 200m
                  memory: 700Mi
            vmselect:
              replicaCount: 2
              cacheMountPath: "/select-cache"
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: "ceph-rbd"
                    resources:
                      requests:
                        storage: 1Gi
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 200Mi
            vminsert:
              replicaCount: 2
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 200Mi
            
        alertmanager:
          enabled: false
        vmalert:
          enabled: false
        grafana: 
          enabled: false
        crds:
          enabled: false

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true