apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://victoriametrics.github.io/helm-charts/'
    targetRevision: 0.29.3
    helm:
      valuesObject:
        cleanupCRD: true
        createCRD: true
        operator:
          disable_prometheus_converter: true
          prometheus_converter_add_argocd_ignore_annotations: true
        resources:
          limits:
            cpu: 120m
            memory: 320Mi
          requests:
            cpu: 80m
            memory: 120Mi
    chart: victoria-metrics-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: victoria-metrics-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
