apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-servicescrape
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/tunamaguro/home-kubernetes-metrics.git
    path: vm-servicescrape
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:   
    automated:
      prune: true